name: Linters

on:
  pull_request:
    branches:
      - main
      - dev

jobs:
  code_check:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.11
      uses: actions/setup-python@v2
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 isort black coverage codecov pytest pytest-cov
    - name: Code quality checks
      run: |
        isort --profile black --check-only -d -w 120 .
        black --check --line-length 120 .
        flake8 --max-line-length 120 -v .
